### ISSUE TITLE
reqest: add 'per frame' to logger

### ISSUE THREAD

**Issue by Mr-Auto** [zappatic/Spelunky2X64DbgPlugin#20]
Not sure if possible, but would be neat to be able to log value per frame, now if you set sample to 16ms it's obviously gets out of sync as it's not exactly 60fps

**Comment by zappatic** [comment]
This is why the default value, when you open the dialog, is 8ms, not 16ms. Google "nyquist criterion" for more info (need to sample at twice the highest frequency to get everything). The plugin can only do polling/sampling, there can't be interrupts or callbacks.

8ms might be pushing your hardware (it does mine a bit, and it's a relatively new PC), so there's not much that can be done if that is the case.

**Comment by Mr-Auto** [comment]
i understand why it's 8ms
does it has to be round to whole ms thou?

**Comment by zappatic** [comment]
Yes, the timer that is used internally has an integer millisecond resolution.
If you need to do exact single frame measurements, I would recommend adding C++ code inside Overlunky to dump the data. There you have direct memory access to everything and C++ speed.
