### ISSUE TITLE
statemachine only for movable

### ISSUE THREAD

**Issue by Mr-Auto** [zappatic/Spelunky2X64DbgPlugin#35]
I think there is a bug in the gathering vtable stuff, non of the floors should have statemachine cuz that's only movable, right?
I'll guess it's just looking for virtual of specific number? should probably also check if it's movable

**Comment by zappatic** [comment]
It checks whether `Entity::handle_state_machine()` is a potentially valid function (not just a `ret`, nor just a `return true/false`), and that function is in `Entity`, not just `Movable`. If those are implemented and don't make sense for floors, it might be that it's just another `return 0` or something that has a different instruction pattern than that which I consider to be a non-implemented function.
See https://github.com/spelunky-fyi/Spelunky2X64DbgPlugin/blob/ad1309c37337cd815f0060a084dcf43d9959ef7e/src/QtHelpers/ItemModelGatherVirtualData.cpp#L537-L564
