### ISSUE TITLE
That latest commit actually broke it

### ISSUE THREAD

**Issue by Dregu** [zappatic/Spelunky2X64DbgPlugin#36]
Autobuild doesn't even work anymore in 1.25.2 after [a7edd1a](https://github.com/spelunky-fyi/Spelunky2X64DbgPlugin/commit/a7edd1a652b4e692e5b21e7fe1c42417ad05e20d), works fine with an old autobuild from november.

**Comment by gmjosack** [comment]
Reverted that commit

**Comment by zappatic** [comment]
For some reason, my main thread is now called 'MainThrd', and I had assumed this was a characteristic of the 1.25.2 release, so the same for everybody. Apparently not.

**Comment by gmjosack** [comment]
Ah thanks for the more permanent fix. I wonder why it can be different.
